In [1]:
import numpy as np

In [2]:
prices = np.array(
    [19.99, 29.99,  14.99, 9.99, 24.99]
)
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [3]:
quatities = np.array(
    [10, 5, 8, 12, 3]
)
quatities

array([10,  5,  8, 12,  3])

In [8]:
total_money = np.sum(prices * quatities)
total_money

np.float64(664.62)

## 2. Analaizin Blog


In [10]:
views = np.array(
    [1000, 500, 800, 1200, 300, 600]
)
views

array([1000,  500,  800, 1200,  300,  600])

In [11]:
max_views = np.max(views)
max_views

np.int64(1200)

In [12]:
min_views = np.min(views)
min_views

np.int64(300)

In [13]:
avg_views = np.round(np.mean(views), 2)
avg_views

np.float64(733.33)

## 3. Splitting Orders

In [15]:
order_ids = np.arange(1001, 1010)
order_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])

In [17]:
batches = np.split(order_ids, 3)
batches

[array([1001, 1002, 1003]),
 array([1004, 1005, 1006]),
 array([1007, 1008, 1009])]

In [20]:
for batche in batches:
    print(batche[0])

1001
1004
1007


## 4. Categorizing Product Rating

In [22]:
ratings = np.array(
    [4.5, 3.2, 2.8, 4.0, 4.1, 3.9, 2.5, 4.7]
)
ratings

array([4.5, 3.2, 2.8, 4. , 4.1, 3.9, 2.5, 4.7])

In [24]:
pozitiv_ratings = ratings[ratings >= 4.0]
pozitiv_ratings

array([4.5, 4. , 4.1, 4.7])

## 5. Calculate Total and AVG qty sold

In [36]:
order_qty = np.array([
    [5, 3, 2, 7],
    [10, 6, 3, 9]
])
otder_qty

array([[ 5,  3,  2,  7],
       [10,  6,  3,  9]])

In [40]:
total_qty_sold = np.sum(order_qty, axis=0)
total_qty_sold

array([15,  9,  5, 16])

In [41]:
avg_qty_sold = np.mean(order_qty, axis=0)
avg_qty_sold

array([7.5, 4.5, 2.5, 8. ])

## 6. Calculate product Rating

In [42]:
product_rating = ([
    [4.5, 3.2, 2.5, 5.0],
    [4.3, 3.8, 1.0, 4.8],
    [2.0, 3.6, 4.7, 0.5]
])
product_rating

[[4.5, 3.2, 2.5, 5.0], [4.3, 3.8, 1.0, 4.8], [2.0, 3.6, 4.7, 0.5]]

In [44]:
avg_rating_per_category = np.mean(product_rating, axis=0)
avg_rating_per_category

array([3.6       , 3.53333333, 2.73333333, 3.43333333])

In [45]:
avg_rating_per_product = np.mean(product_rating, axis=1)
avg_rating_per_product

array([3.8  , 3.475, 2.7  ])

In [46]:
max_rating_per_product = np.max(product_rating, axis=1)
max_rating_per_product

array([5. , 4.8, 4.7])

## 7. Genaration of thr sample stock data

In [47]:
companies = ['Google', 'Aple', 'Amazon']
days = ['Mon 1 April', 'Thu 2 April']
prise_typs = ['Open', 'Close', 'Hith', 'Low']

In [49]:
np.random.seed(1)
stock_prises = np.round(np.random.random(
    (len(companies), len(days), len(prise_typs))
), 3)
stock_prises

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [53]:
for i, company in enumerate(companies):
    print(f'Stock price of company: {company}')
    
    for j, day in enumerate(days):
        print(f'Day: {day}')
        
        for k, prise_type in enumerate(prise_typs):
            print(f'{prise_type} Price: {stock_prises[i, j, k]}')
        print()  
    

Stock price of company: Google
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.72
Hith Price: 0.0
Low Price: 0.302

Day: Thu 2 April
Open Price: 0.147
Close Price: 0.092
Hith Price: 0.186
Low Price: 0.346

Stock price of company: Aple
Day: Mon 1 April
Open Price: 0.397
Close Price: 0.539
Hith Price: 0.419
Low Price: 0.685

Day: Thu 2 April
Open Price: 0.204
Close Price: 0.878
Hith Price: 0.027
Low Price: 0.67

Stock price of company: Amazon
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.559
Hith Price: 0.14
Low Price: 0.198

Day: Thu 2 April
Open Price: 0.801
Close Price: 0.968
Hith Price: 0.313
Low Price: 0.692

