In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(-15, 25, 2)

array([-15, -13, -11,  -9,  -7,  -5,  -3,  -1,   1,   3,   5,   7,   9,
        11,  13,  15,  17,  19,  21,  23])

In [6]:
np.arange(20).reshape([2, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [8]:
np.arange(20).reshape([2, 2, 5])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [13]:
np.arange(20).reshape([2, 2, 5]).reshape([2, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [16]:
np.random.random((10, )).reshape((2, 5))

array([[0.68552056, 0.08579895, 0.22286882, 0.81640263, 0.40605064],
       [0.17094662, 0.33351796, 0.0391727 , 0.76287981, 0.46668718]])

In [21]:
np.random.seed(15)
np.random.randint(10, 80, (4, 3, 3)).flatten()

array([22, 15, 10, 38, 37, 57, 27, 41, 33, 42, 72, 20, 25, 78, 49, 47, 29,
       54, 70, 39, 25, 66, 59, 11, 41, 36, 44, 60, 75, 63, 51, 44, 50, 32,
       73, 66])

In [ ]:
np.