In [2]:
import numpy as np

In [6]:
np.zeros((2, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [34]:
np.random.seed(10)
np.random.random((2, 4))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071]])

In [36]:
np.random.randint(10, 20, size=(2, 4))

array([[10, 18, 16, 14],
       [13, 10, 14, 16]])

In [37]:
np.random.uniform(low=10, high=100, size=(10, 10))

array([[90.17348776, 27.83096317, 12.75549885, 88.98534459, 75.46919623,
        58.67928381, 21.83123372, 47.2300637 , 80.08559274, 62.55112291],
       [26.43682927, 84.3474023 , 19.48616501, 35.52190107, 15.90069397,
        15.07997687, 78.89102364, 11.06092264, 65.0749007 , 39.86940301],
       [60.36835289, 40.19496819, 47.00642914, 16.91699516, 86.77386913,
        49.598871  , 20.97587324, 75.85611622, 22.49042189, 79.01920443],
       [84.8790791 , 37.88002497, 63.78240613, 88.51532139, 98.47187802,
        52.06629511, 88.81700453, 36.6461829 , 21.81619476, 85.85361401],
       [69.31326735, 63.58956445, 49.27183285, 42.06252941, 62.84178327,
        23.45242033, 25.41147384, 45.74480706, 67.41564079, 43.52679568],
       [10.21660852, 59.39347202, 21.42746573, 17.18134126, 31.15347363,
        69.39684525, 29.34578727, 28.27419541, 44.45785998, 30.23855222],
       [20.31839193, 62.47153464, 30.93769565, 60.08663691, 57.14297964,
        41.58624014, 73.47984518, 83.86333671

In [38]:
np.random.choice(np.array([90.17348776, 27.83096317, 12.75549885, 88.98534459, 75.46919623,
        58.67928381, 21.83123372, 47.2300637 , 80.08559274, 62.55112291]), size=5)

array([75.46919623, 47.2300637 , 47.2300637 , 47.2300637 , 62.55112291])