In [3]:
import numpy as np

In [11]:
first = np.array([[1, 2, 3],
                  [4, 5, 6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
first.shape

(2, 3)

In [10]:
first.ndim

2

In [12]:
second = np.array([[7, 8, 9],
                  [10, 11, 12]])

In [13]:
first + second 

array([[ 8, 10, 12],
       [14, 16, 18]])

In [14]:
first[1,1]

np.int64(5)

In [15]:
np.concatenate((first, second))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
np.concatenate((first, second), 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [24]:
np.concatenate((
    np.array([1,2,3,4]), 
    np.array([5,5,7,8]), 
))

array([1, 2, 3, 4, 5, 5, 7, 8])